version: '3.8'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/files/www.conf:/etc/nginx/conf.d/default.conf 
      - ./docker/nginx/files/nginx.conf:/etc/nginx/nginx.conf 
      - ./sample-data/www:/var/www/html 
    restart: on-failure
    depends_on:
      - mysql

  wordpress:
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DEBUG=1
    volumes:
      - ./docker/wordpress/files/php-fpm.conf:/usr/local/etc/php-fpm.conf 
      - ./docker/wordpress/files/php.ini-development:/usr/local/etc/php/php.ini 
      - ./docker/wordpress/files/custom.ini:/usr/local/etc/php/conf.d/custom.ini 
      - ./docker/wordpress/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh 
      - ./sample-data/www:/var/www/html 
    restart: on-failure
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.20
    environment:
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    command: [mysqld, --default-authentication-plugin=mysql_native_password]
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./sample-data/sql/website_v2.sql:/docker-entrypoint-initdb.d/website.sql 
      - ./db:/var/lib/mysql 